### ISSUE TITLE
Unexpected behavior of sum type of structs

### ISSUE THREAD

**Issue by lorentzlasson** [dry-rb/dry-types#233] opened 2018-01-23 13:23 UTC
The `foo` attribute is coerced to be of type `Bar` (left in sum) *even though it's an instance of `Baz`* (right in sum)

```ruby
[1] pry(main)> class Bar < Dry::Struct; constructor_type :schema; attribute :bar, Types::Strict::String; attribute :qux, Types::Strict::String; end
=> Bar
[2] pry(main)> class Baz < Dry::Struct; constructor_type :schema; attribute :baz, Types::Strict::String; end
=> Baz
[3] pry(main)> class Foo < Dry::Struct; attribute :foo, Dry::Types[Bar] | Dry::Types[Baz]; end
=> Foo
[4] pry(main)> Foo.new(foo: Baz.new).foo.class == Baz
=> false
[5] pry(main)> Foo.new(foo: Baz.new(baz: 'zab')).foo.class == Baz
=> false
```
The only exception to this I've found is when both of the summed types have an attribute with the same name and when that attribute is unset.

```ruby
[1] pry(main)> class Bar < Dry::Struct; constructor_type :schema; attribute :bar, Types::Strict::String; attribute :qux, Types::Strict::String; end
=> Bar
[2] pry(main)> class Baz < Dry::Struct; constructor_type :schema; attribute :baz, Types::Strict::String; attribute :qux, Types::Strict::String; end
=> Baz
[3] pry(main)> class Foo < Dry::Struct; attribute :foo, Dry::Types[Bar] | Dry::Types[Baz]; end
=> Foo
[4] pry(main)> Foo.new(foo: Baz.new).foo.class == Baz
=> true
[5] pry(main)> Foo.new(foo: Baz.new(baz: 'zab')).foo.class == Baz
=> true
[6] pry(main)> Foo.new(foo: Baz.new(qux: 'xuq')).foo.class == Baz
=> false
[7] pry(main)> Foo.new(foo: Baz.new(qux: 'xuq')).foo.class
=> Bar
```

**Expected**: instance of `Baz` to always stay `Baz`
**Actual**:  instance of `Baz` sometimes being coerced into `Bar`

What's going on here?

---
dry-types (0.12.2)
dry-struct (0.4.0)

**Comment by flash-gordon** [comment] 2018-01-31 16:51
This is caused by the combination of `contructor_type` and behavior described in https://github.com/dry-rb/dry-struct/issues/24. I'm closing this issue in favor of one in `dry-struct`, I'll push a fix today.

**Closed by flash-gordon** 2018-01-31 16:51 UTC
