### ISSUE TITLE
Sum of Hashes: only first case recognised?

### ISSUE THREAD

**Issue by damncabbage** [dry-rb/dry-types#158] opened 2016-10-14 08:00 UTC
I was experimenting with sums and hashes this evening:

``` ruby
require 'dry-types'
require 'dry-struct'

module Types
  include Dry::Types.module

  Vehicle = Types::Hash.schema(wheels: Types::Strict::Int) | Types::Hash.schema(wing_length: Types::Strict::Float)
end

class Transport < Dry::Struct
  attribute :vehicle, Types::Vehicle
end

puts Transport.new(vehicle: Types::Vehicle[ wing_length: 40.0 ]).inspect # => { vehicle: {} }
puts Transport.new(vehicle: Types::Vehicle[ wheels: 4 ]).inspect         # => { vehicle: { wheels: 4 } }
```

If I reorder the `Vehicle` type definition, suddenly `wing_length` works and `wheels` doesn't; it seems to be order-dependent.

I saw https://github.com/dry-rb/dry-types/issues/81 previously, and I'm _guessing_ this is possibly meant to be supported, but I'm not really sure. Either way, it's currently a silent failure.

Versions (libraries installed a few hours ago without version bounds):
- Ruby 2.2.3
- dry-types 0.9.0
- dry-struct 0.1.0

**Comment by solnic** [comment] 2016-10-15 15:55
Thanks, seems to be a bug. I'll look into this.

**Comment by damncabbage** [comment] 2016-10-17 00:37
Thanks. 😄 

Another case to consider, in case it's helpful:
```ruby
T = Types::Hash.schema(x: Types::Strict::Int) | Types::Hash.schema(x: Types::Strict::Int, y: Types::Strict::String)
```
(Currently fails in the same way.)

**Comment by krasio** [comment] 2016-11-01 10:55
I think this comes from `Dry::Try::Sum#try`:
```ruby
   54:         result = left.try(input) do
   55:           right.try(input)
   56:         end
   57:         byebug
   58: 
=> 59:         return result if result.success?
   60: 
   61:         if block
   62:           yield(result)
   63:         else
(byebug) input
{:wing_length=>5}
(byebug) left.try(input)
#<Dry::Types::Result::Success input={}>
```
Result of `left.try(input)` is success (even if empty) and `right.try(input)` is never executed. Not sure what is the best way to fix this (if a bug).

@damncabbage BTW your example will work with strict schema:
```ruby
2.3.1 :001 > Vehicle = Types::Hash.strict(wheels: Types::Strict::Int) | Types::Hash.strict(wing_length: Types::Strict::Float)
 => #<Dry::Types::Sum ...> 
2.3.1 :002 > Vehicle[ wing_length: 40.0 ]
 => {:wing_length=>40.0} 
2.3.1 :003 > Vehicle[ wheels: 4 ]
 => {:wheels=>4}
```

**Comment by damncabbage** [comment] 2016-11-01 11:12
Huh. Got it. 😄   (Thanks for digging into this.)

**Comment by solnic** [comment] 2016-11-04 11:35
`Types::Hash#schema` is not strict in terms of key presence, so when it's used with an empty hash object, it just returns it back, so the sum returns its result back already without looking at its right side type, that's why using `strict` works here because left side fails, so it tries the right side.

So, yeah, it's not a bug. We gotta document this properly, so I'm leaving this open as a reminder.

**Comment by solnic** [comment] 2016-11-04 11:38
actually...I reported an issue under dry-rb.org repo as that's the place where we gather doc-related todos. Closing this one after all

**Closed by solnic** 2016-11-04 11:38 UTC

**Comment by damncabbage** [comment] 2016-11-04 23:50
Understood; thanks again. :)
