### ISSUE TITLE
Feature Request: filters for input transformation

### ISSUE THREAD

**Issue by mrbongiolo** [dry-rb/dry-types#109] opened 2016-07-10 20:03 UTC
Differently than `constructor` these filters should be applied after construction.
Example:

``` ruby
module Types
  include Dry::Types.module

  Upcased = Dry::Types['strict.string'].filter { |input| input.upcase }

  PlusOne = Dry::Types['coercible.int'].filter { |input| input + 1 }

  DigitsOnly = Dry::Types['strict.string'].filter { |input| input.gsub(/\D/, '') }
end
```

So that by the time the filter runs we can be sure that we have a valid input.

**Comment by flash-gordon** [comment] 2016-07-10 20:44
@mrbongiolo you can chain constructors like this
```ruby
~/dev/dry-types [master] $ ./bin/console
2.3.1 :001 > module Types
2.3.1 :002?>   Upcased = Dry::Types['strict.string'].constructor { |input| input.upcase }
2.3.1 :003?>
2.3.1 :004 >   PlusOne = Dry::Types['coercible.int'].constructor { |input| input + 1 }
2.3.1 :005?>
2.3.1 :006 >   DigitsOnly = Dry::Types['strict.string'].constructor { |input| input.gsub(/\D/, '') }
2.3.1 :007?> end
2.3.1 :008 > Types::Upcased['foo']
 => "FOO"
2.3.1 :009 > Types::PlusOne['2']
 => 3
2.3.1 :010 > Types::DigitsOnly['fdsfs2143sdff']
 => "2143"
2.3.1 :011 >
```
voilà! ✨

**Comment by mrbongiolo** [comment] 2016-07-10 22:19
@flash-gordon thanks for you comment. I know that constructors can be used like that, but the problem with them is that you have to do the logic to ensure you have a valid type, ex: if you try to use: `Types::Upcased[1]` you will get an error of something like Integer not having the `upcase` method, in that case the constructor should be like this: `input.is_a? String ? input.upcase : nil`. Constructors exists to handle complex coercion or data transformation into a valid type, filters would be used after the constructor runs, so that you're sure you have a valid type.

**Comment by flash-gordon** [comment] 2016-07-11 08:34
Oh, sorry, now I see what you mean. The problem is that outer constructor is called unconditionally and I'm not sure if it correct. On the other hand this could be tricky to change. @solnic what do you think about it?

**Comment by solnic** [comment] 2016-07-12 09:10
This might be outside of the scope of this library. I understand that for a simple, standalone examples like yours it feels tempting to just add another method but what we're talking about here is type-safe data transformation and it's a complex problem to solve.

I'm planning to implement it, but I'm not sure where. dry-types + dry-logic will be the foundation for this for sure and *maybe* it will be part of dry-types. Not sure yet.

As far as current functionality goes - types are being built on top of each other. So when you do `Types::Strict::String.constructor(&:upcase)` you're defining that you do always expect a string, and the output value *will also be a string*. Constraints are applied *after* constructor is called because a constructor *may* change the primitive type from invalid to valid.

This means that *it is your job* to implement a constructor in a type-safe way and raise `TypeError` when something unexpected was passed in.

It seems like what you're after is using constraints to protect you from crashing constructors and this is exactly what a type-safe data transformation is about, but as I said this is a whole separate problem to solve that needs its own API.

Regarding the specific method you suggested - `filter` doesn't seem to be a good name because we're not filtering anything, we're *trying* to apply a data transformation, and it *must be guarded* by arbitrary constraints. We have a very solid foundation for this in dry-logic, so it's really a matter of building something on top of it so that we can have a simple API for defining type-safe transformation functions.

I'm gonna leave this one open so that we can discuss how to approach it, where to do it etc.

**Comment by mrbongiolo** [comment] 2016-07-12 12:21
Thanks for the input @solnic. I understand your concerns and I brought this up mostly for discussion, since right now we can accomplish this by using a `constructor` block as @flash-gordon has shown.

**Comment by flash-gordon** [comment] 2018-02-01 21:39
It's not a bad idea but time showed we don't need it that much, up to this point at least. I'll close this but we can continue the discussion [on the forum](https://discourse.dry-rb.org/) if needed.

**Closed by flash-gordon** 2018-02-01 21:39 UTC
Labels: discussion, feature
